// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu8tlLdNX3rephXuTRrKoIPykXDGz4Xvs',
    appId: '1:284367357091:web:015514919010f085daab16',
    messagingSenderId: '284367357091',
    projectId: 'dtshop-822f6',
    authDomain: 'dtshop-822f6.firebaseapp.com',
    storageBucket: 'dtshop-822f6.appspot.com',
    measurementId: 'G-B4XX2G9BZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCd0zn48znQnC7ftX0DhAbrUE-7tLA9xA',
    appId: '1:284367357091:android:95e17bc4d0dd1b9ddaab16',
    messagingSenderId: '284367357091',
    projectId: 'dtshop-822f6',
    storageBucket: 'dtshop-822f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvYhxqt4myNVh1CtP8rYtRQJC9ffbxCTg',
    appId: '1:284367357091:ios:8ae9957abe2c38a3daab16',
    messagingSenderId: '284367357091',
    projectId: 'dtshop-822f6',
    storageBucket: 'dtshop-822f6.appspot.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvYhxqt4myNVh1CtP8rYtRQJC9ffbxCTg',
    appId: '1:284367357091:ios:8ae9957abe2c38a3daab16',
    messagingSenderId: '284367357091',
    projectId: 'dtshop-822f6',
    storageBucket: 'dtshop-822f6.appspot.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu8tlLdNX3rephXuTRrKoIPykXDGz4Xvs',
    appId: '1:284367357091:web:e97d85c4274f02fbdaab16',
    messagingSenderId: '284367357091',
    projectId: 'dtshop-822f6',
    authDomain: 'dtshop-822f6.firebaseapp.com',
    storageBucket: 'dtshop-822f6.appspot.com',
    measurementId: 'G-Z6ZJVY8S16',
  );
}
